application: paymysitter
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /img
  static_dir: img
  secure: always

- url: /examplesecuredirectory
  script: exampleseparateapp.app
  login: required
  secure: always

- url: /examplesecuredirectory/.*
  script: exampleseparateapp.app
  login: required
  secure: always

- url: .*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"

error_handlers:
  - error_code: over_quota
    file: gaeoverquota.html